### PR TITLE
Fix  bid strips should have a transparent background

### PR DESCRIPTION
**Pull request by mrphemi**
Remove the white background color from the `MarketParticipant.tsx` component.
Screenshot 2022-11-29 at 10 15 18

### CODE REVIEW

**Review by curiousways — APPROVED** [review]

**Comment by alexandermendes** [comment]
Are you sure? This was there to prevent the background of the walkthrough showing through when the bar is partially filled. For example, this is the design:

image

And with this change, this is what it will look like for real (notice the trees from the background showing through the bar):

image

**Comment by curiousways** [comment]
Ah, good point.

Are we using an RGBA value to alter the colour? If so, could we use a HEX/RGB value so we don't see a transparency?

**Comment by alexandermendes** [comment]
Yeah that could be another option, I can't tell if this change was solving another problem in the first place though. Seems like the actual intention of it was to make the above happen, which may or may not be what we want!

**Comment by alexandermendes** [comment]
Ah, I just saw the linked issue https://github.com/curiousways/marketdesign/issues/78. Ok makes sense then.

**Pull request merged**
