### PR TITLE
More walkthrough 0 fixes

### PR DESCRIPTION
**Pull request by alexandermendes**
This should address the remaining feedback for the intro walkthrough. There's just one point remaining that I'm not too sure about:

> Screen 15: Would like to link away here to a new tab that shows Ben’s text on the Balanced Winner Contribution Rule calculations.

Where is this text and where would we like the link to appear? In the sidebar content perhaps? I'm also not totally sure which one "Screen 15" is. Is that before or after we merged Screen 12 and Screen 13 🤔

### CODE REVIEW

**Comment by curiousways** [comment]
> Where is this text and where would we like the link to appear? In the sidebar content perhaps? I'm also not totally sure which one "Screen 15" is. Is that before or after we merged Screen 12 and Screen 13

On this @alexandermendes - we will link to another URL on the site (a page we need to create called "Balanced Winner Contribution Rule Calculations"). I'm assuming screen 15 is the last screen on the walkthrough.

**Comment by curiousways** [comment]
Screenshot 2022-12-13 at 16 19 29

On this screen (screen 5), it needs to say 2 Bio & 3 Water Quality

Screenshot 2022-12-13 at 16 19 07

**Comment by alexandermendes** [comment]
Hmm, well spotted, except under the "Wording" section of the intro walkthrough feedback we also have:

> Screen 5: Bring bullet pointed credit quantities into paragraph text; that is: “The development highlighted on the map, for example, will only be allowed to proceed if the developer sources 1 biodiversity credit and 2 water quality credits”.

So I think this sidebar content is referring to the buyer project, which does have 1 bio and 2 water quality, but it is all quite confusing 😅

**Comment by curiousways** [comment]
Screenshot 2022-12-13 at 17 06 11

Looks like we need to align these left?

Screenshot 2022-12-13 at 17 05 48

**Comment by alexandermendes** [comment]
That one should be fixed in one of the other PRs I think...although off the top of my head I can't remember which one!

**Comment by alexandermendes** [comment]
Yeah this one I think https://github.com/curiousways/marketdesign/pull/98 (because we had more market outcome related things there)

**Review by curiousways — APPROVED** [review]

**Pull request merged**
