### PR TITLE
Buyer 1 fixes

### PR DESCRIPTION
**Pull request by alexandermendes**
image

### CODE REVIEW

**Review by curiousways — CHANGES_REQUESTED** [review]
> Screen 10: The project cost should remain at £120,000 in the my project box (even though the developer enters a bid of £80,000 … they are again bidding below value)

User needs to add a bid of 80,000, but we validate at 100,000

Screenshot 2022-11-29 at 07 27 12

**Comment by curiousways** [comment]
> > Screen 10: The project cost should remain at £120,000 in the my project box (even though the developer enters a bid of £80,000 … they are again bidding below value)
> 
> User needs to add a bid of 80,000, but we validate at 100,000
> 
> Screenshot 2022-11-29 at 07 27 12

Perhaps it's the copy that's wrong here, that it should say "Submit a bid of £100,000 and then solve the market."?

**Review by curiousways — COMMENTED** [review]
> Screen Limited Information Market: Market solution at £100,000 Solution is wrong. Winners are only Seller 1 & 2 and Buyer 2 & 3:

When testing this, the winners are Buyers 1 &2 and Sellers 1 & 2

**Comment by alexandermendes** [comment]
> User needs to add a bid of 80,000, but we validate at 100,000

Oops, ok so I think "Screen 10" here means scenario 1.3, in which case yep, it's wrong and will fix. Matching up the way they see "screens" with the way the scenarios/stages actually work has been a little tricky!

**Comment by alexandermendes** [comment]
> > Screen Limited Information Market: Market solution at £100,000 Solution is wrong. Winners are only Seller 1 & 2 and Buyer 2 & 3:
> 
> When testing this, the winners are Buyers 1 &2 and Sellers 1 & 2

Hmm, yeah this is one of those cases where the wrote some words and then said "see the table", and the table doesn't match up with the words, where there is no buyer 3!

image

So I'm not sure what to do in those cases, I have assumed that their original tables are what they actually want.

**Comment by curiousways** [comment]
thanks @alexandermendes - got it. I am noting these instances on the sheet and will check these with client.

**Review by curiousways — APPROVED** [review]

**Pull request merged**
