### PR TITLE
Sandbox end buttons

### PR DESCRIPTION
**Pull request by alexandermendes**
From the sandbox feedback:

> Once the market has played out the user should get 3 options. "Replay Market", "Shuffle Market" or "Return to Market Choice". Recall each market has a list of states, where each state is characterised by a players having slightly different demand and supply. When a user chooses a market, the code should randomly choose one state to play out. When the user presses "Replay", that just sends the user back to play this identical market again ... or more technically, to play out this same "state" of the market. "Shuffle" should return the user to the start of this market to play again, but with a different randomly selected choice of state. "Return" just takes the user back to the Index screen.

And looks like:

image

### CODE REVIEW

**Comment by curiousways** [comment]
@alexandermendes - i'm testing this one, but cannot see what changes occur when moving through the choices, is this expected behaviour you can see here?

https://user-images.githubusercontent.com/71117886/207407515-9144046f-5c89-4551-a8af-9ae3c12d11fe.mp4

**Comment by alexandermendes** [comment]
Ah right, yeah well the vast majority of the walkthroughs/scenarios they have given us only have one state anyway, which does make this shuffle button slightly pointless! In fact the only one with two states is the one called "Prototype market with 2 states".

Maybe we should hide the shuffle button if there's only one state (although that wasn't mentioned) 🤔

**Comment by curiousways** [comment]
Yeah I agree - let’s check for state and perhaps disable the button if it won’t do anything, or hide it completely if the design still looks OK

--
David Flindall
Director


curiousways.com
+44 (0) 7870 583 147

Instagram  LinkedIn

The company accepts no liability for the content of this email, or for the consequences of any   actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by alexandermendes** [comment]
> Yeah I agree - let’s check for state and perhaps disable the button if it won’t do anything, or hide it completely if the design still looks OK

Done!

image

**Review by curiousways — APPROVED** [review]

**Pull request merged**
